# Generated by Django 6.0.1 on 2026-03-18 00:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("providers", "0015_providerprofile_excellence_badges_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("campaign_key", models.CharField(db_index=True, max_length=80)),
                (
                    "campaign_kind",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("label", models.CharField(blank=True, default="", max_length=160)),
                (
                    "object_type",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=50)),
                ("source_app", models.CharField(blank=True, default="", max_length=50)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("popup_opens", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("leads", models.PositiveIntegerField(default=0)),
                ("conversions", models.PositiveIntegerField(default=0)),
                (
                    "ctr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-day", "-impressions", "-clicks", "campaign_key"],
            },
        ),
        migrations.CreateModel(
            name="ExtrasDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("sku", models.CharField(db_index=True, max_length=80)),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("extra_type", models.CharField(blank=True, default="", max_length=20)),
                ("purchases", models.PositiveIntegerField(default=0)),
                ("activations", models.PositiveIntegerField(default=0)),
                ("consumptions", models.PositiveIntegerField(default=0)),
                ("credits_consumed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-day", "-purchases", "sku"],
            },
        ),
        migrations.CreateModel(
            name="ProviderDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("profile_views", models.PositiveIntegerField(default=0)),
                ("chat_starts", models.PositiveIntegerField(default=0)),
                ("requests_received", models.PositiveIntegerField(default=0)),
                ("requests_accepted", models.PositiveIntegerField(default=0)),
                ("requests_completed", models.PositiveIntegerField(default=0)),
                ("requests_cancelled", models.PositiveIntegerField(default=0)),
                (
                    "accept_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "-day",
                    "-requests_received",
                    "-profile_views",
                    "provider_id",
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                (
                    "plan_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                (
                    "plan_title",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("tier", models.CharField(blank=True, default="", max_length=20)),
                ("checkouts_started", models.PositiveIntegerField(default=0)),
                ("activations", models.PositiveIntegerField(default=0)),
                ("upgrades", models.PositiveIntegerField(default=0)),
                ("renewals", models.PositiveIntegerField(default=0)),
                ("churns", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-day", "-activations", "plan_code"],
            },
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="analytics_a_event_n_aeeca0_idx",
            old_name="analytics_e_event_n_c7f9f9_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="analytics_a_channel_c23175_idx",
            old_name="analytics_e_channel_03326e_idx",
        ),
        migrations.RenameIndex(
            model_name="analyticsevent",
            new_name="analytics_a_object__f7c1f4_idx",
            old_name="analytics_e_object__b70c68_idx",
        ),
        migrations.AddIndex(
            model_name="campaigndailystats",
            index=models.Index(
                fields=["day", "campaign_key"], name="analytics_c_day_0affe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaigndailystats",
            index=models.Index(
                fields=["day", "campaign_kind"], name="analytics_c_day_863fda_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaigndailystats",
            unique_together={("day", "campaign_key")},
        ),
        migrations.AddIndex(
            model_name="extrasdailystats",
            index=models.Index(
                fields=["day", "sku"], name="analytics_e_day_62051e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extrasdailystats",
            index=models.Index(
                fields=["day", "extra_type"], name="analytics_e_day_7b2ad8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="extrasdailystats",
            unique_together={("day", "sku")},
        ),
        migrations.AddField(
            model_name="providerdailystats",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_daily_stats",
                to="providers.providerprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptiondailystats",
            index=models.Index(
                fields=["day", "plan_code"], name="analytics_s_day_f5202f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptiondailystats",
            index=models.Index(
                fields=["day", "tier"], name="analytics_s_day_e3ec0c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscriptiondailystats",
            unique_together={("day", "plan_code")},
        ),
        migrations.AddIndex(
            model_name="providerdailystats",
            index=models.Index(
                fields=["day", "provider"], name="analytics_p_day_6a3144_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="providerdailystats",
            unique_together={("day", "provider")},
        ),
    ]
