from django.urls import path

from .views import (
    access,
    analytics,
    auth,
    client_portal,
    content,
    excellence,
    extras,
    home,
    moderation,
    promo,
    requests,
    reviews,
    subscriptions,
    support,
    verification,
)


app_name = "dashboard_v2"


urlpatterns = [
    path("login/", auth.login_view, name="login"),
    path("otp/", auth.otp_view, name="otp"),
    path("logout/", auth.logout_view, name="logout"),
    path("", home.home_view, name="home"),
    path("analytics/overview/", analytics.analytics_overview_view, name="analytics_overview"),
    path("analytics/reports/", analytics.analytics_reports_index_view, name="analytics_reports_index"),
    path("analytics/exports/", analytics.analytics_exports_view, name="analytics_exports"),
    path("access/users/", access.users_list_view, name="users_list"),
    path("access/users/<int:user_id>/", access.user_detail_view, name="user_detail"),
    path("requests/", requests.requests_list_view, name="requests_list"),
    path("requests/<int:request_id>/", requests.request_detail_view, name="request_detail"),
    path("requests/<int:request_id>/actions/assign/", requests.request_assign_action, name="request_assign_action"),
    path("requests/<int:request_id>/actions/status/", requests.request_status_action, name="request_status_action"),
    path("support/", support.support_list_view, name="support_list"),
    path("support/<int:ticket_id>/", support.support_detail_view, name="support_detail"),
    path("support/<int:ticket_id>/actions/assign/", support.support_assign_action, name="support_assign_action"),
    path("support/<int:ticket_id>/actions/status/", support.support_status_action, name="support_status_action"),
    path("content/", content.content_home_view, name="content_home"),
    path("content/blocks/<str:key>/update/", content.content_block_update_action, name="content_block_update_action"),
    path("content/docs/<str:doc_type>/upload/", content.content_doc_upload_action, name="content_doc_upload_action"),
    path("content/links/update/", content.content_links_update_action, name="content_links_update_action"),
    path("content/portfolio/", content.content_portfolio_list_view, name="content_portfolio_list"),
    path("content/portfolio/<int:item_id>/actions/delete/", content.content_portfolio_delete_action, name="content_portfolio_delete_action"),
    path("content/spotlights/", content.content_spotlight_list_view, name="content_spotlight_list"),
    path("content/spotlights/<int:item_id>/actions/delete/", content.content_spotlight_delete_action, name="content_spotlight_delete_action"),
    path("moderation/", moderation.moderation_list_view, name="moderation_list"),
    path("moderation/<int:case_id>/", moderation.moderation_detail_view, name="moderation_detail"),
    path("moderation/<int:case_id>/actions/assign/", moderation.moderation_assign_action, name="moderation_assign_action"),
    path("moderation/<int:case_id>/actions/status/", moderation.moderation_status_action, name="moderation_status_action"),
    path("moderation/<int:case_id>/actions/decision/", moderation.moderation_decision_action, name="moderation_decision_action"),
    path("reviews/", reviews.reviews_list_view, name="reviews_list"),
    path("reviews/<int:review_id>/", reviews.reviews_detail_view, name="reviews_detail"),
    path("reviews/<int:review_id>/actions/moderate/", reviews.reviews_moderate_action, name="reviews_moderate_action"),
    path("reviews/<int:review_id>/actions/respond/", reviews.reviews_respond_action, name="reviews_respond_action"),
    path("excellence/", excellence.excellence_home_view, name="excellence_home"),
    path("excellence/candidates/<int:candidate_id>/", excellence.excellence_candidate_detail_view, name="excellence_candidate_detail"),
    path("excellence/candidates/<int:candidate_id>/actions/approve/", excellence.excellence_candidate_approve_action, name="excellence_candidate_approve_action"),
    path("excellence/awards/<int:award_id>/actions/revoke/", excellence.excellence_award_revoke_action, name="excellence_award_revoke_action"),
    path("promo/", promo.promo_requests_list_view, name="promo_requests_list"),
    path("promo/requests/<int:promo_id>/", promo.promo_request_detail_view, name="promo_request_detail"),
    path("promo/requests/<int:promo_id>/actions/assign/", promo.promo_request_assign_action, name="promo_request_assign_action"),
    path("promo/requests/<int:promo_id>/actions/ops-status/", promo.promo_request_ops_status_action, name="promo_request_ops_status_action"),
    path("promo/requests/<int:promo_id>/actions/quote/", promo.promo_quote_action, name="promo_quote_action"),
    path("promo/requests/<int:promo_id>/actions/reject/", promo.promo_reject_action, name="promo_reject_action"),
    path("promo/requests/<int:promo_id>/actions/activate/", promo.promo_activate_action, name="promo_activate_action"),
    path("promo/inquiries/", promo.promo_inquiries_list_view, name="promo_inquiries_list"),
    path("promo/inquiries/<int:ticket_id>/", promo.promo_inquiry_detail_view, name="promo_inquiry_detail"),
    path("promo/inquiries/<int:ticket_id>/actions/assign/", promo.promo_inquiry_assign_action, name="promo_inquiry_assign_action"),
    path("promo/inquiries/<int:ticket_id>/actions/status/", promo.promo_inquiry_status_action, name="promo_inquiry_status_action"),
    path("promo/inquiries/<int:ticket_id>/actions/profile/", promo.promo_inquiry_profile_action, name="promo_inquiry_profile_action"),
    path("promo/pricing/", promo.promo_pricing_view, name="promo_pricing"),
    path("promo/pricing/actions/update/", promo.promo_pricing_update_action, name="promo_pricing_update_action"),
    path("promo/banners/", promo.promo_banners_list_view, name="promo_banners_list"),
    path("verification/", verification.verification_requests_list_view, name="verification_requests_list"),
    path("verification/<int:verification_id>/", verification.verification_request_detail_view, name="verification_request_detail"),
    path("verification/<int:verification_id>/actions/finalize/", verification.verification_finalize_action, name="verification_finalize_action"),
    path("verification/<int:verification_id>/actions/activate/", verification.verification_activate_action, name="verification_activate_action"),
    path("verification/requirements/<int:req_id>/actions/decision/", verification.verification_requirement_decision_action, name="verification_requirement_decision_action"),
    path("subscriptions/", subscriptions.subscriptions_list_view, name="subscriptions_list"),
    path("subscriptions/plans/", subscriptions.subscriptions_plans_list_view, name="subscriptions_plans_list"),
    path("subscriptions/requests/<int:subscription_id>/", subscriptions.subscription_request_detail_view, name="subscription_request_detail"),
    path("subscriptions/accounts/<int:subscription_id>/", subscriptions.subscription_account_detail_view, name="subscription_account_detail"),
    path("subscriptions/payments/<int:subscription_id>/", subscriptions.subscription_payment_detail_view, name="subscription_payment_detail"),
    path("subscriptions/<int:subscription_id>/actions/refresh/", subscriptions.subscription_refresh_action, name="subscription_refresh_action"),
    path("subscriptions/<int:subscription_id>/actions/activate/", subscriptions.subscription_activate_action, name="subscription_activate_action"),
    path("subscriptions/requests/<int:subscription_id>/actions/add-note/", subscriptions.subscription_request_add_note_action, name="subscription_request_add_note_action"),
    path("subscriptions/requests/<int:subscription_id>/actions/set-status/", subscriptions.subscription_request_set_status_action, name="subscription_request_set_status_action"),
    path("subscriptions/requests/<int:subscription_id>/actions/assign/", subscriptions.subscription_request_assign_action, name="subscription_request_assign_action"),
    path("extras/", extras.extras_requests_list_view, name="extras_requests_list"),
    path("extras/requests/<int:request_id>/", extras.extras_request_detail_view, name="extras_request_detail"),
    path("extras/requests/<int:request_id>/actions/assign/", extras.extras_request_assign_action, name="extras_request_assign_action"),
    path("extras/requests/<int:request_id>/actions/status/", extras.extras_request_status_action, name="extras_request_status_action"),
    path("extras/purchases/<int:purchase_id>/actions/activate/", extras.extra_purchase_activate_action, name="extra_purchase_activate_action"),
    path("extras/clients/", extras.extras_clients_list_view, name="extras_clients_list"),
    path("extras/catalog/", extras.extras_catalog_list_view, name="extras_catalog_list"),
    path("extras/catalog/<int:item_id>/actions/toggle/", extras.extras_catalog_toggle_action, name="extras_catalog_toggle_action"),
    path("extras/finance/", extras.extras_finance_list_view, name="extras_finance_list"),
    path("client-portal/", client_portal.client_portal_home_view, name="client_portal_home"),
    path("client-portal/requests/", client_portal.client_portal_requests_list_view, name="client_portal_requests_list"),
    path("client-portal/requests/<int:request_id>/", client_portal.client_portal_request_detail_view, name="client_portal_request_detail"),
    path("client-portal/services/", client_portal.client_portal_services_list_view, name="client_portal_services_list"),
    path("client-portal/services/<int:purchase_id>/", client_portal.client_portal_service_detail_view, name="client_portal_service_detail"),
    path("client-portal/reports/", client_portal.client_portal_reports_view, name="client_portal_reports"),
    path("client-portal/account-statement/", client_portal.client_portal_account_statement_view, name="client_portal_account_statement"),
    path("client-portal/payments/<int:invoice_id>/", client_portal.client_portal_payment_detail_view, name="client_portal_payment_detail"),
    path("client-portal/profile/", client_portal.client_portal_profile_view, name="client_portal_profile"),
    path("client-portal/settings/", client_portal.client_portal_settings_view, name="client_portal_settings"),
]
