# Generated by Django 6.0.1 on 2026-02-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("request_type", models.CharField(choices=[
                    ("helpdesk", "دعم ومساعدة (HD)"),
                    ("promo", "إعلانات وترويج (MD)"),
                    ("verification", "توثيق (AD)"),
                    ("subscription", "ترقية واشتراكات (SD)"),
                    ("extras", "خدمات إضافية (P)"),
                ], max_length=20)),
                ("status", models.CharField(choices=[
                    ("new", "جديد"),
                    ("in_progress", "تحت المعالجة"),
                    ("returned", "معاد للعميل"),
                    ("closed", "مغلق"),
                    ("completed", "مكتمل"),
                    ("rejected", "مرفوض"),
                    ("pending_payment", "بانتظار الدفع"),
                    ("active", "مفعل"),
                    ("expired", "منتهي"),
                    ("cancelled", "ملغي"),
                ], default="new", max_length=30)),
                ("priority", models.CharField(choices=[
                    ("basic", "الأساسية"),
                    ("leading", "الريادية"),
                    ("professional", "الاحترافية"),
                    ("low", "منخفضة"),
                    ("normal", "عادية"),
                    ("high", "عالية"),
                ], default="normal", max_length=20)),
                ("assigned_team_code", models.SlugField(blank=True, max_length=50)),
                ("assigned_team_name", models.CharField(blank=True, max_length=120)),
                ("source_app", models.CharField(blank=True, max_length=50)),
                ("source_model", models.CharField(blank=True, max_length=80)),
                ("source_object_id", models.CharField(blank=True, max_length=50)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_unified_requests", to=settings.AUTH_USER_MODEL)),
                ("requester", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="unified_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedRequestAssignmentLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_team_code", models.SlugField(blank=True, max_length=50)),
                ("to_team_code", models.SlugField(blank=True, max_length=50)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unified_request_assignment_changed_logs", to=settings.AUTH_USER_MODEL)),
                ("from_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unified_request_assignment_from_logs", to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_logs", to="unified_requests.unifiedrequest")),
                ("to_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unified_request_assignment_to_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="UnifiedRequestMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="metadata_record", to="unified_requests.unifiedrequest")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_unified_request_metadata", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UnifiedRequestStatusLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(choices=[
                    ("new", "جديد"),
                    ("in_progress", "تحت المعالجة"),
                    ("returned", "معاد للعميل"),
                    ("closed", "مغلق"),
                    ("completed", "مكتمل"),
                    ("rejected", "مرفوض"),
                    ("pending_payment", "بانتظار الدفع"),
                    ("active", "مفعل"),
                    ("expired", "منتهي"),
                    ("cancelled", "ملغي"),
                ], max_length=30)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="unified_request_status_changed_logs", to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_logs", to="unified_requests.unifiedrequest")),
            ],
            options={"ordering": ["-id"]},
        ),
        migrations.AddIndex(
            model_name="unifiedrequest",
            index=models.Index(fields=["request_type", "status"], name="unified_requ_request_bcc4e6_idx"),
        ),
        migrations.AddIndex(
            model_name="unifiedrequest",
            index=models.Index(fields=["assigned_user", "status"], name="unified_requ_assigne_2e4298_idx"),
        ),
        migrations.AddIndex(
            model_name="unifiedrequest",
            index=models.Index(fields=["source_app", "source_model", "source_object_id"], name="unified_requ_source__5f39f7_idx"),
        ),
        migrations.AddConstraint(
            model_name="unifiedrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_app__gt", ""), ("source_model__gt", ""), ("source_object_id__gt", "")),
                fields=("source_app", "source_model", "source_object_id"),
                name="uq_unified_request_source_ref",
            ),
        ),
    ]
