# Generated by Django 6.0.1 on 2026-03-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_servicerequest_subcategories_m2m"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="servicerequestdispatch",
            new_name="marketplace_dispatc_7ea5ec_idx",
            old_name="marketplace__dispatc_0fd4b8_idx",
        ),
        migrations.RenameIndex(
            model_name="servicerequestdispatch",
            new_name="marketplace_request_d1e821_idx",
            old_name="marketplace__request_b516ad_idx",
        ),
    ]
