# Generated by Django 6.0.1 on 2026-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_servicerequest_request_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "جديد"),
                    ("provider_accepted", "تم قبول الطلب"),
                    ("awaiting_client", "بانتظار اعتماد العميل"),
                    ("in_progress", "تحت التنفيذ"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
