# Generated by Django 5.1.2 on 2026-05-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0014_alter_servicerequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequestattachment",
            name="source",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("provider_progress", "Provider progress update"),
                    ("provider_completion", "Provider completion"),
                ],
                db_index=True,
                default="client",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="servicerequestattachment",
            name="status_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="marketplace.requeststatuslog",
            ),
        ),
    ]
