# Generated by Django 5.1.2 on 2026-05-08 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0015_add_progress_attachment_link"),
        ("providers", "0032_visibility_blocks_role_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequestPaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "confirmed_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("currency", models.CharField(default="SAR", max_length=10)),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("iban", models.CharField(blank=True, default="", max_length=34)),
                (
                    "qr_image_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reference", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوحة"),
                            ("paid", "مدفوعة بالكامل"),
                            ("closed", "مغلقة"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_request_payment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_request_payment_plans",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plan",
                        to="marketplace.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestPaymentInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "بانتظار الدفع"),
                            ("receipt_uploaded", "بانتظار تأكيد المزود"),
                            ("confirmed", "مؤكدة"),
                            ("rejected", "مرفوضة"),
                            ("cancelled", "ملغاة"),
                        ],
                        default="pending_payment",
                        max_length=24,
                    ),
                ),
                (
                    "provider_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "client_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="marketplace/payment_receipts/%Y/%m/%d/",
                    ),
                ),
                ("receipt_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_payment_installments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt_uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_payment_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_payment_installments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_installments",
                        to="marketplace.servicerequest",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="marketplace.servicerequestpaymentplan",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "sequence"),
                        name="uniq_payment_installment_plan_sequence",
                    )
                ],
            },
        ),
    ]
