# Generated by Django 6.0.1 on 2026-05-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0018_servicerequest_provider_inputs_has_financial_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequestattachment",
            name="source",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("client_response", "Client response to provider input"),
                    ("provider_progress", "Provider progress update"),
                    ("provider_completion", "Provider completion"),
                ],
                db_index=True,
                default="client",
                max_length=24,
            ),
        ),
    ]
