# Generated by Django 6.0.1 on 2026-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationpreference_audience_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("request_created", "تم إنشاء طلب"),
                    ("request_assigned", "تم إسناد الطلب"),
                    ("offer_created", "تم تقديم عرض"),
                    ("offer_selected", "تم اختيار عرضك"),
                    ("status_changed", "تغيرت حالة الطلب"),
                    ("message_new", "رسالة جديدة"),
                    ("payment_received", "تم تسجيل سداد"),
                    ("ad_visit", "تم تسجيل زيارة إعلان"),
                    ("scheduled_message_sent", "تم تنفيذ رسالة مجدولة"),
                    ("client_reminder_due", "تذكير عميل مستحق"),
                    ("provider_joined_category", "انضم مزود جديد إلى الفئة"),
                    ("category_highlight_published", "تم نشر لمحة ضمن الفئة"),
                ],
                max_length=50,
            ),
        ),
    ]
