# Generated by Django 5.1.2 on 2026-03-09 19:03

import apps.promo.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0003_promo_targeting_and_pricing"),
        ("providers", "0015_providerprofile_excellence_badges_cache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان البانر"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "صورة"), ("video", "فيديو")],
                        default="image",
                        max_length=10,
                        verbose_name="نوع الوسائط",
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        upload_to="promo/home_banners/%Y/%m/",
                        validators=[
                            apps.promo.validators.validate_file_size,
                            apps.promo.validators.validate_extension,
                        ],
                        verbose_name="ملف الوسائط",
                    ),
                ),
                ("link_url", models.URLField(blank=True, verbose_name="رابط التوجيه")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعل")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ البداية"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ النهاية"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_home_banners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="home_banners",
                        to="providers.providerprofile",
                        verbose_name="مقدم الخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "بانر الصفحة الرئيسية",
                "verbose_name_plural": "بانرات الصفحة الرئيسية",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
