# Generated by Django 6.0.1 on 2026-03-09 20:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0004_homebanner"),
        ("providers", "0015_providerprofile_excellence_badges_cache"),
        ("support", "0003_seed_default_support_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("home_banner", "بنر الصفحة الرئيسية"),
                            ("featured_specialists", "شريط أبرز المختصين"),
                            ("portfolio_showcase", "شريط البنرات والمشاريع"),
                            ("snapshots", "شريط اللمحات"),
                            ("search_results", "الظهور في قوائم البحث"),
                            ("promo_messages", "الرسائل الدعائية"),
                            ("sponsorship", "الرعاية"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("day", "لكل يوم"),
                            ("campaign", "لكل حملة"),
                            ("month", "لكل شهر"),
                        ],
                        default="day",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10s", "كل 10 ثواني"),
                            ("20s", "كل 20 ثانية"),
                            ("30s", "كل 30 ثانية"),
                            ("60s", "كل 60 ثانية"),
                            ("300s", "كل 5 دقائق"),
                            ("900s", "كل 15 دقيقة"),
                            ("1800s", "كل 30 دقيقة"),
                            ("3600s", "كل ساعة"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "search_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "الأول"),
                            ("second", "الثاني"),
                            ("top5", "ضمن أول 5"),
                            ("top10", "ضمن أول 10"),
                            ("normal", "عادي"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "message_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("notification", "رسائل التنبيه الدعائية"),
                            ("chat", "رسائل المحادثات الدعائية"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قاعدة تسعير ترويجي",
                "verbose_name_plural": "قواعد التسعير الترويجي",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="promorequest",
            name="ops_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promorequest",
            name="ops_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="promorequest",
            name="ops_status",
            field=models.CharField(
                choices=[
                    ("new", "جديد"),
                    ("in_progress", "تحت المعالجة"),
                    ("completed", "مكتمل"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="promoadprice",
            name="ad_type",
            field=models.CharField(
                choices=[
                    ("bundle", "طلب ترويج متعدد الخدمات"),
                    ("banner_home", "بانر الصفحة الرئيسية"),
                    ("banner_category", "بانر صفحة القسم"),
                    ("banner_search", "بانر صفحة البحث"),
                    ("popup_home", "نافذة منبثقة رئيسية"),
                    ("popup_category", "نافذة منبثقة داخل قسم"),
                    ("featured_top5", "تمييز ضمن أول 5"),
                    ("featured_top10", "تمييز ضمن أول 10"),
                    ("boost_profile", "تعزيز ملف مقدم الخدمة"),
                    ("push_notification", "إشعار دفع (Push)"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="promorequest",
            name="ad_type",
            field=models.CharField(
                choices=[
                    ("bundle", "طلب ترويج متعدد الخدمات"),
                    ("banner_home", "بانر الصفحة الرئيسية"),
                    ("banner_category", "بانر صفحة القسم"),
                    ("banner_search", "بانر صفحة البحث"),
                    ("popup_home", "نافذة منبثقة رئيسية"),
                    ("popup_category", "نافذة منبثقة داخل قسم"),
                    ("featured_top5", "تمييز ضمن أول 5"),
                    ("featured_top10", "تمييز ضمن أول 10"),
                    ("boost_profile", "تعزيز ملف مقدم الخدمة"),
                    ("push_notification", "إشعار دفع (Push)"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="promorequest",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("10s", "كل 10 ثواني"),
                    ("20s", "كل 20 ثانية"),
                    ("30s", "كل 30 ثانية"),
                    ("60s", "كل 60 ثانية"),
                    ("300s", "كل 5 دقائق"),
                    ("900s", "كل 15 دقيقة"),
                    ("1800s", "كل 30 دقيقة"),
                    ("3600s", "كل ساعة"),
                ],
                default="60s",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="promorequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "جديد"),
                    ("in_review", "قيد المراجعة"),
                    ("quoted", "تم التسعير"),
                    ("pending_payment", "بانتظار الدفع"),
                    ("active", "مفعل"),
                    ("completed", "مكتمل"),
                    ("rejected", "مرفوض"),
                    ("expired", "منتهي"),
                    ("cancelled", "ملغي"),
                ],
                default="new",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="PromoInquiryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detailed_request_url", models.URLField(blank=True)),
                (
                    "documentation_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "operator_comment",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_inquiries",
                        to="promo.promorequest",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_profile",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف استفسار ترويجي",
                "verbose_name_plural": "ملفات الاستفسارات الترويجية",
            },
        ),
        migrations.CreateModel(
            name="PromoRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("home_banner", "بنر الصفحة الرئيسية"),
                            ("featured_specialists", "شريط أبرز المختصين"),
                            ("portfolio_showcase", "شريط البنرات والمشاريع"),
                            ("snapshots", "شريط اللمحات"),
                            ("search_results", "الظهور في قوائم البحث"),
                            ("promo_messages", "الرسائل الدعائية"),
                            ("sponsorship", "الرعاية"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("send_at", models.DateTimeField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10s", "كل 10 ثواني"),
                            ("20s", "كل 20 ثانية"),
                            ("30s", "كل 30 ثانية"),
                            ("60s", "كل 60 ثانية"),
                            ("300s", "كل 5 دقائق"),
                            ("900s", "كل 15 دقيقة"),
                            ("1800s", "كل 30 دقيقة"),
                            ("3600s", "كل ساعة"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "search_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("default", "قائمة البحث الافتراضية"),
                            ("main_results", "نتائج البحث الرئيسية"),
                            ("category_match", "نتائج البحث المطابقة لتصنيف المختص"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "search_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "الأول"),
                            ("second", "الثاني"),
                            ("top5", "ضمن أول 5"),
                            ("top10", "ضمن أول 10"),
                            ("normal", "عادي"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "target_category",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "target_city",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("redirect_url", models.URLField(blank=True)),
                (
                    "message_title",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "message_body",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("use_notification_channel", models.BooleanField(default=False)),
                ("use_chat_channel", models.BooleanField(default=False)),
                (
                    "sponsor_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("sponsor_url", models.URLField(blank=True)),
                ("sponsorship_months", models.PositiveIntegerField(default=0)),
                (
                    "attachment_specs",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "operator_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=0)),
                (
                    "pricing_rule_code",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="promo.promorequest",
                    ),
                ),
                (
                    "target_portfolio_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_request_items",
                        to="providers.providerportfolioitem",
                    ),
                ),
                (
                    "target_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promo_request_items",
                        to="providers.providerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "بند طلب ترويج",
                "verbose_name_plural": "بنود طلبات الترويج",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="promoasset",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="promo.promorequestitem",
            ),
        ),
    ]
