# Generated by Django 6.0.1 on 2026-03-09 20:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vat_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="نسبة ضريبة القيمة المضافة (%)",
                    ),
                ),
                (
                    "subscription_grace_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="أيام السماح بعد انتهاء الاشتراك"
                    ),
                ),
                (
                    "subscription_yearly_duration_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="مدة الاشتراك السنوي (أيام)"
                    ),
                ),
                (
                    "subscription_monthly_duration_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="مدة الاشتراك الشهري (أيام)"
                    ),
                ),
                (
                    "verification_validity_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="مدة صلاحية التوثيق (أيام)"
                    ),
                ),
                (
                    "verification_currency",
                    models.CharField(
                        default="SAR", max_length=10, verbose_name="عملة رسوم التوثيق"
                    ),
                ),
                (
                    "verification_reminder_days_before",
                    models.PositiveIntegerField(
                        default=30, verbose_name="تنبيه قبل انتهاء التوثيق (أيام)"
                    ),
                ),
                (
                    "promo_vat_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="نسبة ضريبة الترويج (%)",
                    ),
                ),
                (
                    "promo_min_campaign_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="الحد الأدنى لمدة الحملة (ساعات)"
                    ),
                ),
                (
                    "subscription_reminder_days_before",
                    models.CharField(
                        default="7,3,1",
                        help_text="مثال: 7,3,1 — يعني تنبيه قبل 7 و 3 و 1 أيام",
                        max_length=100,
                        verbose_name="تنبيهات قبل انتهاء الاشتراك (أيام، مفصولة بفاصلة)",
                    ),
                ),
                (
                    "extras_default_duration_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="مدة الخدمة الإضافية الافتراضية (أيام)"
                    ),
                ),
                (
                    "upload_max_file_size_mb",
                    models.PositiveIntegerField(
                        default=100, verbose_name="الحد الأقصى لحجم الملف (MB)"
                    ),
                ),
                (
                    "excellence_review_cycle_days",
                    models.PositiveIntegerField(
                        default=90, verbose_name="دورة مراجعة التميز (أيام)"
                    ),
                ),
                (
                    "excellence_min_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("4.50"),
                        max_digits=3,
                        verbose_name="الحد الأدنى للتقييم للخدمة المتميزة",
                    ),
                ),
                (
                    "excellence_min_orders",
                    models.PositiveIntegerField(
                        default=5,
                        verbose_name="الحد الأدنى للطلبات المكتملة (الإنجاز العالي)",
                    ),
                ),
                (
                    "excellence_top_n_club",
                    models.PositiveIntegerField(
                        default=100, verbose_name="حجم نادي الكبار (top N)"
                    ),
                ),
                (
                    "export_pdf_max_rows",
                    models.PositiveIntegerField(
                        default=200, verbose_name="الحد الأقصى لصفوف PDF"
                    ),
                ),
                (
                    "export_xlsx_max_rows",
                    models.PositiveIntegerField(
                        default=2000, verbose_name="الحد الأقصى لصفوف XLSX"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعدادات المنصة",
                "verbose_name_plural": "إعدادات المنصة",
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("sub_expiry", "انتهاء الاشتراك"),
                            ("ver_expiry", "انتهاء التوثيق"),
                            ("promo_complete", "انتهاء الحملة الترويجية"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        help_text="PK of the related object (Subscription, Badge, Campaign…)"
                    ),
                ),
                (
                    "days_before",
                    models.PositiveIntegerField(
                        help_text="How many days before expiry this reminder was sent"
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل التنبيهات",
                "verbose_name_plural": "سجلات التنبيهات",
                "indexes": [
                    models.Index(
                        fields=["reminder_type", "reference_id", "days_before"],
                        name="core_remind_reminde_dd2df5_idx",
                    )
                ],
                "unique_together": {
                    ("user", "reminder_type", "reference_id", "days_before")
                },
            },
        ),
    ]
