# Generated by Django 6.0.1 on 2026-03-13 02:39

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_platformconfig_operational_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformconfig",
            name="promo_base_prices",
            field=models.JSONField(
                blank=True,
                default=apps.core.models.default_promo_base_prices,
                verbose_name="الأسعار الأساسية legacy للترويج",
            ),
        ),
        migrations.AlterField(
            model_name="platformconfig",
            name="promo_frequency_multipliers",
            field=models.JSONField(
                blank=True,
                default=apps.core.models.default_promo_frequency_multipliers,
                verbose_name="مضاعفات تكرار الظهور legacy للترويج",
            ),
        ),
        migrations.AlterField(
            model_name="platformconfig",
            name="promo_position_multipliers",
            field=models.JSONField(
                blank=True,
                default=apps.core.models.default_promo_position_multipliers,
                verbose_name="مضاعفات مواقع الظهور legacy للترويج",
            ),
        ),
    ]
