# Generated by Django 6.0.1 on 2026-03-19 01:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_platformconfig_promo_base_prices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfig",
            name="extras_vat_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                max_digits=5,
                verbose_name="نسبة ضريبة الخدمات الإضافية (%)",
            ),
        ),
    ]
