# Generated by Django 6.0.1 on 2026-04-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_platformconfig_promo_frequency_multipliers"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfig",
            name="promo_asset_image_max_file_size_mb",
            field=models.PositiveIntegerField(
                default=10,
                help_text="الحد الأعلى لحجم الصورة المرفقة في طلبات الترويج.",
                verbose_name="حد مرفقات الترويج - الصور (MB)",
            ),
        ),
        migrations.AddField(
            model_name="platformconfig",
            name="promo_asset_other_max_file_size_mb",
            field=models.PositiveIntegerField(
                default=10,
                help_text="الحد الأعلى لحجم أي مرفق إضافي (غير صورة/فيديو/PDF) في طلبات الترويج.",
                verbose_name="حد مرفقات الترويج - ملفات إضافية (MB)",
            ),
        ),
        migrations.AddField(
            model_name="platformconfig",
            name="promo_asset_pdf_max_file_size_mb",
            field=models.PositiveIntegerField(
                default=10,
                help_text="الحد الأعلى لحجم ملف PDF المرفق في طلبات الترويج.",
                verbose_name="حد مرفقات الترويج - PDF (MB)",
            ),
        ),
        migrations.AddField(
            model_name="platformconfig",
            name="promo_asset_video_max_file_size_mb",
            field=models.PositiveIntegerField(
                default=20,
                help_text="الحد الأعلى لحجم الفيديو المرفق في طلبات الترويج.",
                verbose_name="حد مرفقات الترويج - الفيديو (MB)",
            ),
        ),
        migrations.AddField(
            model_name="platformconfig",
            name="promo_home_banner_image_max_file_size_mb",
            field=models.PositiveIntegerField(
                default=10,
                help_text="الحد الأعلى لصورة بنر الصفحة الرئيسية ضمن طلبات الترويج.",
                verbose_name="حد مرفقات بنر الرئيسية - صورة (MB)",
            ),
        ),
        migrations.AddField(
            model_name="platformconfig",
            name="promo_home_banner_video_max_file_size_mb",
            field=models.PositiveIntegerField(
                default=20,
                help_text="الحد الأعلى لفيديو بنر الصفحة الرئيسية (MP4) ضمن طلبات الترويج.",
                verbose_name="حد مرفقات بنر الرئيسية - فيديو MP4 (MB)",
            ),
        ),
    ]
