# Generated by Django 6.0.1 on 2026-02-24 18:01

import apps.content.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("onboarding_first_time", "الدخول أول مرة"),
                            ("onboarding_intro", "صفحة التعريف"),
                            ("settings_help", "معلومات المساعدة"),
                            ("settings_info", "معلومات الإعدادات"),
                        ],
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("title_ar", models.CharField(max_length=255)),
                ("body_ar", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_site_content_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SiteLegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("terms", "الشروط والأحكام"),
                            ("privacy", "سياسة الخصوصية"),
                            ("regulations", "الأنظمة والتشريعات"),
                            ("prohibited_services", "الخدمات الممنوعة"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="site_legal/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "txt"]
                            ),
                            apps.content.models.validate_legal_document_file,
                        ],
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=40)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_site_legal_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_url", models.URLField(blank=True)),
                ("whatsapp_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("android_store", models.URLField(blank=True)),
                ("ios_store", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_site_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site links",
            },
        ),
    ]
