# Generated by Django 6.0.1 on 2026-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_remove_hero_search_content_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontentblock",
            name="key",
            field=models.CharField(
                choices=[
                    ("onboarding_first_time", "الدخول أول مرة"),
                    ("onboarding_intro", "صفحة التعريف"),
                    ("onboarding_get_started", "صفحة الانطلاق"),
                    ("home_categories_title", "الرئيسية - عنوان التصنيفات"),
                    ("home_providers_title", "الرئيسية - عنوان مزودي الخدمة"),
                    ("home_banners_title", "الرئيسية - عنوان العروض الترويجية"),
                    ("login_title", "الدخول - العنوان"),
                    ("login_description", "الدخول - الوصف"),
                    ("login_phone_hint", "الدخول - تلميح الجوال"),
                    ("login_submit_label", "الدخول - زر الإرسال"),
                    ("login_guest_label", "الدخول - زر الزائر"),
                    ("signup_title", "التسجيل - العنوان"),
                    ("signup_description", "التسجيل - الوصف"),
                    ("signup_submit_label", "التسجيل - زر الإكمال"),
                    ("signup_terms_label", "التسجيل - نص الشروط"),
                    ("twofa_title", "التحقق - العنوان"),
                    ("twofa_description", "التحقق - الوصف"),
                    ("twofa_submit_label", "التحقق - زر التأكيد"),
                    ("twofa_resend_label", "التحقق - إعادة الإرسال"),
                    ("twofa_change_phone_label", "التحقق - تغيير الجوال"),
                    ("twofa_success_resend_label", "التحقق - نجاح إعادة الإرسال"),
                    ("twofa_phone_notice", "التحقق - تم إرسال الرمز إلى"),
                    ("twofa_resend_prompt", "التحقق - لم يصلك الرمز"),
                    ("about_hero_title", "من نحن - عنوان الهيرو"),
                    ("about_hero_subtitle", "من نحن - الوصف المختصر"),
                    ("about_section_about", "من نحن - قسم من نحن"),
                    ("about_section_vision", "من نحن - قسم الرؤية"),
                    ("about_section_goals", "من نحن - قسم الأهداف"),
                    ("about_section_values", "من نحن - قسم القيم"),
                    ("about_section_app", "من نحن - قسم التطبيق"),
                    ("about_social_title", "من نحن - عنوان التواصل"),
                    ("about_website_label", "من نحن - زر الموقع الرسمي"),
                    ("terms_page_title", "الشروط - عنوان الصفحة"),
                    ("terms_empty_label", "الشروط - حالة الفراغ"),
                    ("terms_open_document_label", "الشروط - زر فتح المستند"),
                    ("terms_file_only_hint", "الشروط - تلميح المستند المرفق"),
                    ("terms_missing_document_hint", "الشروط - تلميح غياب المستند"),
                    ("contact_gate_title", "التواصل - عنوان بوابة الدخول"),
                    ("contact_gate_description", "التواصل - وصف بوابة الدخول"),
                    ("contact_gate_login_label", "التواصل - زر تسجيل الدخول"),
                    ("contact_page_title", "التواصل - عنوان الصفحة"),
                    ("contact_refresh_label", "التواصل - زر التحديث"),
                    ("contact_new_ticket_label", "التواصل - زر بلاغ جديد"),
                    ("contact_list_title", "التواصل - عنوان قائمة البلاغات"),
                    ("contact_create_title", "التواصل - عنوان إنشاء البلاغ"),
                    ("contact_detail_title", "التواصل - عنوان تفاصيل البلاغ"),
                    ("contact_empty_label", "التواصل - حالة فراغ البلاغات"),
                    ("contact_team_placeholder", "التواصل - اختيار فريق الدعم"),
                    ("contact_description_label", "التواصل - حقل التفاصيل"),
                    ("contact_attachments_label", "التواصل - حقل المرفقات"),
                    ("contact_cancel_label", "التواصل - زر الإلغاء"),
                    ("contact_submit_label", "التواصل - زر إرسال البلاغ"),
                    ("contact_reply_placeholder", "التواصل - حقل التعليق"),
                    ("contact_reply_submit_label", "التواصل - زر إرسال التعليق"),
                    ("settings_help", "معلومات المساعدة"),
                    ("settings_info", "معلومات الإعدادات"),
                ],
                max_length=80,
                unique=True,
            ),
        ),
    ]
