# Generated by Django 6.0.1 on 2026-04-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_add_site_identity_and_social_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingContentBlock",
            fields=[],
            options={
                "verbose_name": "هوية المنصة",
                "verbose_name_plural": "هوية المنصة",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.sitecontentblock",),
        ),
        migrations.CreateModel(
            name="HomePageFallbackBannerBlock",
            fields=[],
            options={
                "verbose_name": "بنر الرئيسية الافتراضي",
                "verbose_name_plural": "بنر الرئيسية الافتراضي",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.sitecontentblock",),
        ),
    ]
