# Generated by Django 6.0.1 on 2026-04-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_add_app_intro_preview_key"),
        ("content", "0020_brandingcontentblock_homepagefallbackbannerblock"),
    ]

    operations = []
