# Generated by Django 6.0.1 on 2026-04-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_merge_20260415_1503"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformLogoBlock",
            fields=[],
            options={
                "verbose_name": "شعار المنصة",
                "verbose_name_plural": "شعار المنصة",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("content.sitecontentblock",),
        ),
    ]