# Generated by Django 5.1.2 on 2026-03-02 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0013_make_city_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="providerfollow",
            name="uniq_follow_user_provider",
        ),
        migrations.RemoveConstraint(
            model_name="providerlike",
            name="uniq_like_user_provider",
        ),
        migrations.RemoveConstraint(
            model_name="providerportfoliolike",
            name="uniq_like_user_portfolio_item",
        ),
        migrations.RemoveConstraint(
            model_name="providerportfoliosave",
            name="uniq_save_user_portfolio_item",
        ),
        migrations.RemoveConstraint(
            model_name="providerspotlightlike",
            name="uniq_like_user_spotlight_item",
        ),
        migrations.RemoveConstraint(
            model_name="providerspotlightsave",
            name="uniq_save_user_spotlight_item",
        ),
        migrations.AddField(
            model_name="providerfollow",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providerlike",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providerportfoliolike",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providerportfoliosave",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providerspotlightlike",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providerspotlightsave",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="providerfollow",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "role_context"),
                name="uniq_follow_user_provider_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerlike",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "role_context"),
                name="uniq_like_user_provider_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerportfoliolike",
            constraint=models.UniqueConstraint(
                fields=("user", "item", "role_context"),
                name="uniq_like_user_portfolio_item_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerportfoliosave",
            constraint=models.UniqueConstraint(
                fields=("user", "item", "role_context"),
                name="uniq_save_user_portfolio_item_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerspotlightlike",
            constraint=models.UniqueConstraint(
                fields=("user", "item", "role_context"),
                name="uniq_like_user_spotlight_item_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerspotlightsave",
            constraint=models.UniqueConstraint(
                fields=("user", "item", "role_context"),
                name="uniq_save_user_spotlight_item_role",
            ),
        ),
    ]
