# Generated by Django 6.0.1 on 2026-04-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0017_providercategory_accepts_urgent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaudiRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name_ar", "id"],
            },
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="SaudiCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="providers.saudiregion",
                    ),
                ),
            ],
            options={
                "ordering": ["region__sort_order", "sort_order", "name_ar", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "name_ar"), name="uniq_saudi_city_per_region"
                    )
                ],
            },
        ),
    ]
