# Generated by Django 6.0.1 on 2026-05-02 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0020_providercontentcomment_providercontentshare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderVisibilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_blocks",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_visibility_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderSpotlightVisibilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "spotlight_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_blocks",
                        to="providers.providerspotlightitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_spotlight_visibility_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="providervisibilityblock",
            constraint=models.UniqueConstraint(fields=("user", "provider"), name="uniq_provider_visibility_block_user_provider"),
        ),
        migrations.AddConstraint(
            model_name="providerspotlightvisibilityblock",
            constraint=models.UniqueConstraint(fields=("user", "spotlight_item"), name="uniq_spotlight_visibility_block_user_item"),
        ),
        migrations.AddIndex(
            model_name="providervisibilityblock",
            index=models.Index(fields=["user", "provider"], name="providers_p_user_id_f8f47e_idx"),
        ),
        migrations.AddIndex(
            model_name="providerspotlightvisibilityblock",
            index=models.Index(fields=["user", "spotlight_item"], name="providers_p_user_id_e5059c_idx"),
        ),
    ]