# Generated by Django 6.0.1 on 2026-05-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0021_providervisibilityblock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providercontentcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="providers.providercontentcomment",
            ),
        ),
    ]