# Generated by Django 6.0.1 on 2026-05-03 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0023_providerprofile_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderPortfolioVisibilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_blocks",
                        to="providers.providerportfolioitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_portfolio_visibility_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="providerportfoliovisibilityblock",
            constraint=models.UniqueConstraint(fields=("user", "portfolio_item"), name="uniq_portfolio_visibility_block_user_item"),
        ),
        migrations.AddIndex(
            model_name="providerportfoliovisibilityblock",
            index=models.Index(fields=["user", "portfolio_item"], name="providers_p_user_id_7d63fe_idx"),
        ),
    ]