# Generated by Django 6.0.1 on 2026-05-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0030_providercontentcomment_role_context"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="providerportfoliovisibilityblock",
            new_name="providers_p_user_id_231e11_idx",
            old_name="providers_p_user_id_7d63fe_idx",
        ),
        migrations.RenameIndex(
            model_name="providerspotlightvisibilityblock",
            new_name="providers_p_user_id_6a01d5_idx",
            old_name="providers_p_user_id_e5059c_idx",
        ),
        migrations.RenameIndex(
            model_name="providervisibilityblock",
            new_name="providers_p_user_id_b0bf0a_idx",
            old_name="providers_p_user_id_f8f47e_idx",
        ),
        migrations.AlterField(
            model_name="providercontentcommentlike",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
    ]
