# Generated by Django 6.0.1 on 2026-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0031_rename_providers_p_user_id_7d63fe_idx_providers_p_user_id_231e11_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="providerportfoliovisibilityblock",
            name="uniq_portfolio_visibility_block_user_item",
        ),
        migrations.RemoveConstraint(
            model_name="providerspotlightvisibilityblock",
            name="uniq_spotlight_visibility_block_user_item",
        ),
        migrations.RemoveConstraint(
            model_name="providervisibilityblock",
            name="uniq_provider_visibility_block_user_provider",
        ),
        migrations.RemoveIndex(
            model_name="providerportfoliovisibilityblock",
            name="providers_p_user_id_231e11_idx",
        ),
        migrations.RemoveIndex(
            model_name="providerspotlightvisibilityblock",
            name="providers_p_user_id_6a01d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="providervisibilityblock",
            name="providers_p_user_id_b0bf0a_idx",
        ),
        migrations.AddField(
            model_name="providerportfoliovisibilityblock",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providerspotlightvisibilityblock",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="providervisibilityblock",
            name="role_context",
            field=models.CharField(
                choices=[("client", "عميل"), ("provider", "مزود خدمة")],
                db_index=True,
                default="client",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="providerportfoliovisibilityblock",
            constraint=models.UniqueConstraint(
                fields=("user", "portfolio_item", "role_context"),
                name="uniq_portfolio_visibility_block_user_item_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerspotlightvisibilityblock",
            constraint=models.UniqueConstraint(
                fields=("user", "spotlight_item", "role_context"),
                name="uniq_spotlight_visibility_block_user_item_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="providervisibilityblock",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "role_context"),
                name="uniq_provider_visibility_block_user_provider_role",
            ),
        ),
        migrations.AddIndex(
            model_name="providerportfoliovisibilityblock",
            index=models.Index(fields=["user", "portfolio_item", "role_context"], name="provprt_user_item_role_idx"),
        ),
        migrations.AddIndex(
            model_name="providerspotlightvisibilityblock",
            index=models.Index(fields=["user", "spotlight_item", "role_context"], name="provspt_user_item_role_idx"),
        ),
        migrations.AddIndex(
            model_name="providervisibilityblock",
            index=models.Index(fields=["user", "provider", "role_context"], name="provvis_user_provider_role_idx"),
        ),
    ]