# Generated by Django 6.0.1 on 2026-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0004_rename_verificatio_code_0d4980_idx_verificatio_code_290ca1_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[("blue", "شارة زرقاء"), ("green", "شارة خضراء")],
                        max_length=20,
                        unique=True,
                        verbose_name="نوع الشارة",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="رسم التوثيق (شامل الضريبة)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", max_length=10, verbose_name="العملة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="ملاحظة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "قاعدة تسعير توثيق",
                "verbose_name_plural": "قواعد تسعير التوثيق",
                "ordering": ["badge_type"],
            },
        ),
    ]
