# Generated by Django 6.0.1 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_supportticket_entrypoint"),
        ("verification", "0005_add_verification_pricing_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationInquiryProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detailed_request_url", models.URLField(blank=True)),
                ("operator_comment", models.CharField(blank=True, default="", max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="linked_inquiries",
                        to="verification.verificationrequest",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="verification_profile",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف استفسار التوثيق",
                "verbose_name_plural": "ملفات استفسارات التوثيق",
            },
        ),
    ]
