# Generated by Django 6.0.1 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0006_verificationinquiryprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationBlueProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("individual", "فرد"), ("business", "منشأة")],
                        max_length=20,
                    ),
                ),
                ("official_number", models.CharField(max_length=32)),
                ("official_date", models.DateField()),
                ("verified_name", models.CharField(max_length=180)),
                ("is_name_approved", models.BooleanField(default=False)),
                ("verification_source", models.CharField(default="elm", max_length=40)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=models.CASCADE,
                        related_name="blue_profile",
                        to="verification.verificationrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "بيانات الشارة الزرقاء",
                "verbose_name_plural": "بيانات الشارة الزرقاء",
            },
        ),
    ]
