# Generated by Django 6.0.1 on 2026-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0008_verificationrequirement_evidence_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "جديد"),
                    ("in_review", "تحت المعالجة"),
                    ("rejected", "مرفوض"),
                    ("approved", "معتمد"),
                    ("pending_payment", "بانتظار الدفع"),
                    ("active", "مفعل"),
                    ("expired", "منتهي"),
                ],
                default="new",
                max_length=25,
            ),
        ),
    ]
