# Generated by Django 6.0.1 on 2026-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("invoice_created", "إنشاء فاتورة"),
                    ("invoice_paid", "دفع فاتورة"),
                    ("subscription_started", "بدء اشتراك"),
                    ("subscription_active", "تفعيل اشتراك"),
                    ("subscription_request_assigned", "إسناد طلب اشتراك"),
                    ("subscription_request_status_changed", "تغيير حالة طلب اشتراك"),
                    ("subscription_request_note_added", "إضافة ملاحظة طلب اشتراك"),
                    ("subscription_account_note_added", "إضافة ملاحظة حساب اشتراك"),
                    ("subscription_account_renew_requested", "طلب تجديد اشتراك"),
                    ("subscription_account_upgrade_requested", "طلب ترقية اشتراك"),
                    ("subscription_account_cancelled", "إلغاء اشتراك"),
                    ("subscription_payment_checkout_opened", "فتح شاشة دفع اشتراك"),
                    ("subscription_payment_completed", "إتمام دفع اشتراك"),
                    ("verify_request_created", "طلب توثيق"),
                    ("verify_request_approved", "اعتماد توثيق"),
                    ("verify_request_rejected", "رفض توثيق"),
                    ("promo_request_created", "طلب إعلان"),
                    ("promo_request_quoted", "تسعير إعلان"),
                    ("promo_request_active", "تفعيل إعلان"),
                    ("extra_purchase_created", "شراء إضافة"),
                    ("extra_purchase_active", "تفعيل إضافة"),
                    ("access_profile_updated", "تحديث صلاحيات تشغيل"),
                    ("access_profile_created", "إنشاء صلاحيات تشغيل"),
                    ("access_profile_revoked", "سحب صلاحيات تشغيل"),
                    ("access_profile_unrevoked", "إلغاء سحب صلاحيات تشغيل"),
                    ("content_block_updated", "تحديث بلوك محتوى"),
                    ("content_document_uploaded", "رفع مستند قانوني"),
                    ("content_links_updated", "تحديث روابط المنصة"),
                    ("review_moderated", "تعديل حالة مراجعة"),
                    ("review_response_added", "إضافة رد إداري على مراجعة"),
                    ("login_otp_sent", "إرسال OTP"),
                    ("login_otp_verified", "تأكيد OTP"),
                ],
                max_length=60,
            ),
        ),
    ]
