# Generated by Django 6.0.1 on 2026-04-14 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras_portal", "0001_initial"),
        (
            "marketplace",
            "0012_rename_marketplace__dispatc_0fd4b8_idx_marketplace_dispatc_7ea5ec_idx_and_more",
        ),
        ("providers", "0020_providercontentcomment_providercontentshare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="برنامج الولاء", max_length=120)),
                (
                    "points_per_completed_request",
                    models.PositiveIntegerField(default=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_program",
                        to="providers.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_balance", models.IntegerField(default=0)),
                ("total_earned", models.IntegerField(default=0)),
                ("total_redeemed", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="extras_portal.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-points_balance"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "كسب"),
                            ("redeem", "استبدال"),
                            ("adjustment", "تعديل"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="extras_portal.loyaltymembership",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_transactions",
                        to="marketplace.servicerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderPotentialClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "يدوي"),
                            ("contact_list", "من قائمة التواصل"),
                            ("system", "تلقائي"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potential_clients",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="potential_client_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="loyaltymembership",
            constraint=models.UniqueConstraint(
                fields=("program", "user"), name="uniq_loyalty_membership_program_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerpotentialclient",
            constraint=models.UniqueConstraint(
                fields=("provider", "user"), name="uniq_potential_client_provider_user"
            ),
        ),
    ]
