# Generated by Django 5.1.2 on 2026-04-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extras_portal",
            "0002_loyaltyprogram_loyaltymembership_loyaltytransaction_and_more",
        ),
        ("providers", "0020_providercontentcomment_providercontentshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDataSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unified_request_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "request_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("section_key", models.CharField(default="reports", max_length=50)),
                ("option_key", models.CharField(db_index=True, max_length=100)),
                ("data_json", models.JSONField(default=dict)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_snapshots",
                        to="providers.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "unified_request_id", "option_key"],
                        name="extras_port_provide_97b71b_idx",
                    )
                ],
            },
        ),
    ]
