# Generated by Django 5.1.2 on 2026-04-19 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras_portal", "0003_report_data_snapshot"),
        ("providers", "0020_providercontentcomment_providercontentshare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "reminder_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("reminder_date", models.DateField(blank=True, null=True)),
                ("reminder_time", models.TimeField(blank=True, null=True)),
                ("loyalty_points_added", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_records",
                        to="providers.providerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras_portal_client_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "user"),
                        name="uniq_client_record_provider_user",
                    )
                ],
            },
        ),
    ]
