# Generated by Django 5.1.2 on 2026-04-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras_portal", "0004_client_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrecord",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientrecord",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
