# Generated by Django 5.1.2 on 2026-04-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras_portal", "0005_client_record_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrasportalfinancesettings",
            name="account_holder_first_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="extrasportalfinancesettings",
            name="account_holder_last_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="extrasportalfinancesettings",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
