# Generated by Django 6.0.1 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_invoicelineitem_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_currency",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_event_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_provider",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(event_id__gt=""),
                fields=("provider", "event_id"),
                name="billing_webhookevent_provider_event_unique",
            ),
        ),
        migrations.AlterField(
            model_name="paymentattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "بدأت"),
                    ("redirected", "تم التحويل"),
                    ("success", "ناجحة"),
                    ("failed", "فشلت"),
                    ("cancelled", "ملغاة"),
                    ("refunded", "مسترجعة"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
    ]
