# Generated by Django 6.0.1 on 2026-04-15 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_invoicelineitem_item_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="الموظف الذي أنشأ الفاتورة يدوياً",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
