from django.urls import path
from .views import (
    change_password_view,
    change_username_view,
    ThrottledTokenObtainPairView,
    ThrottledTokenRefreshView,
    biometric_enroll,
    biometric_login,
    biometric_revoke,
    complete_registration,
    skip_completion,
    delete_account_view,
    heartbeat_view,
    logout_view,
    me_view,
    otp_send,
    otp_verify,
    request_phone_change_view,
    confirm_phone_change_view,
    username_availability,
    wallet_view,
)

app_name = "accounts"

urlpatterns = [
    path("otp/send/", otp_send, name="otp_send"),
    path("otp/verify/", otp_verify, name="otp_verify"),
    path("biometric/enroll/", biometric_enroll, name="biometric_enroll"),
    path("biometric/login/", biometric_login, name="biometric_login"),
    path("biometric/revoke/", biometric_revoke, name="biometric_revoke"),
    path("username-availability/", username_availability, name="username_availability"),
    path("complete/", complete_registration, name="complete"),
    path("skip-completion/", skip_completion, name="skip_completion"),
    path("wallet/", wallet_view, name="wallet"),
    path("change-username/", change_username_view, name="change_username"),
    path("change-password/", change_password_view, name="change_password"),
    path("token/", ThrottledTokenObtainPairView.as_view(), name="token"),
    path("token/refresh/", ThrottledTokenRefreshView.as_view(), name="token_refresh"),
    path("me/", me_view, name="me"),
    path("me/request-phone-change/", request_phone_change_view, name="request_phone_change"),
    path("me/confirm-phone-change/", confirm_phone_change_view, name="confirm_phone_change"),
    path("logout/", logout_view, name="logout"),
    path("delete/", delete_account_view, name="delete_account"),
    path("heartbeat/", heartbeat_view, name="heartbeat"),
]
