# Generated by Django 6.0.1 on 2026-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_normalize_current_subscription_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="banner_images_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="banner_images_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="competitive_visibility_delay_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="competitive_visibility_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="direct_chat_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="direct_chat_quota",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="feature_bullets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="notifications_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="promotional_chat_messages_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="promotional_notification_messages_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="reminder_policy_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="reminder_schedule_hours",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="storage_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="storage_multiplier",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="storage_policy",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="storage_upload_max_mb",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="support_is_priority",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="support_priority",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="support_sla_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="support_sla_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="verification_blue_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="verification_green_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
