# Generated by Django 6.0.1 on 2026-03-17 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("source_app", models.CharField(blank=True, max_length=50)),
                ("source_model", models.CharField(blank=True, max_length=80)),
                ("source_object_id", models.CharField(blank=True, max_length=50)),
                ("source_label", models.CharField(blank=True, max_length=120)),
                ("category", models.CharField(blank=True, default="", max_length=40)),
                ("reason", models.CharField(max_length=120)),
                ("details", models.CharField(blank=True, max_length=500)),
                ("summary", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("under_review", "قيد المراجعة"),
                            ("action_taken", "تم اتخاذ إجراء"),
                            ("dismissed", "مرفوض / بدون إجراء"),
                            ("escalated", "مصعّد"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("normal", "عادية"),
                            ("high", "عالية"),
                            ("critical", "حرجة"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("assigned_team_code", models.SlugField(blank=True)),
                ("assigned_team_name", models.CharField(blank=True, max_length=120)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linked_support_ticket_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "linked_support_ticket_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_cases_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_cases_targeted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_cases_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ModerationActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "تم الإنشاء"),
                            ("assigned", "تم الإسناد"),
                            ("status_changed", "تغيير الحالة"),
                            ("decision_recorded", "تسجيل قرار"),
                            ("note_added", "إضافة ملاحظة"),
                        ],
                        max_length=30,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_assignment_from_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_assignment_to_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="moderation.moderationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ModerationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_code",
                    models.CharField(
                        choices=[
                            ("hide", "إخفاء"),
                            ("delete", "حذف"),
                            ("warn", "تنبيه"),
                            ("no_action", "بدون إجراء"),
                            ("escalate", "تصعيد"),
                            ("close", "إغلاق"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("outcome", models.JSONField(blank=True, default=dict)),
                ("is_final", models.BooleanField(default=True)),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_decisions_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="moderation.moderationcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddIndex(
            model_name="moderationcase",
            index=models.Index(
                fields=["status", "severity", "created_at"],
                name="moderation__status_51a70b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationcase",
            index=models.Index(
                fields=["source_app", "source_model", "source_object_id"],
                name="moderation__source__ff2371_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationcase",
            index=models.Index(
                fields=["assigned_to", "status"], name="moderation__assigne_78362b_idx"
            ),
        ),
    ]
