# Generated by Django 6.0.1 on 2026-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="رمز الخدمة (SKU)"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="عنوان الخدمة"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="السعر (بدون ضريبة)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR", max_length=10, verbose_name="العملة"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="الترتيب"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "خدمة إضافية (كتالوج)",
                "verbose_name_plural": "كتالوج الخدمات الإضافية",
                "ordering": ["sort_order", "sku"],
            },
        ),
    ]
