# Generated by Django 6.0.1 on 2026-02-24 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_alter_servicerequest_request_type_and_more"),
        ("providers", "0011_providerportfolioitem_thumbnail_and_more"),
        ("reviews", "0004_review_provider_reply_edited_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="management_reply",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="review",
            name="management_reply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="management_reply_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_management_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_moderated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderation_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="review",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("approved", "معتمد"),
                    ("rejected", "مرفوض"),
                    ("hidden", "مخفي"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["moderation_status", "created_at"],
                name="reviews_rev_moderat_9f44f0_idx",
            ),
        ),
    ]
