# Generated by Django 6.0.1 on 2026-03-17 19:41

from django.db import migrations, models


PERMISSION_ROWS = [
    {
        "code": "moderation.assign",
        "name_ar": "إسناد حالات الإشراف",
        "dashboard_code": "moderation",
        "description": "يتيح إسناد حالات مركز الإشراف.",
        "sort_order": 10,
    },
    {
        "code": "moderation.resolve",
        "name_ar": "معالجة حالات الإشراف",
        "dashboard_code": "moderation",
        "description": "يتيح تغيير حالة القضية وتسجيل القرار النهائي.",
        "sort_order": 20,
    },
    {
        "code": "content.hide_delete",
        "name_ar": "إخفاء/حذف المحتوى",
        "dashboard_code": "content",
        "description": "إجراء حساس على المحتوى العام.",
        "sort_order": 30,
    },
    {
        "code": "support.assign",
        "name_ar": "إسناد تذاكر الدعم",
        "dashboard_code": "support",
        "description": "يتيح إسناد تذاكر الدعم للمشغلين.",
        "sort_order": 40,
    },
    {
        "code": "support.resolve",
        "name_ar": "إغلاق/معالجة تذاكر الدعم",
        "dashboard_code": "support",
        "description": "يتيح تحديث حالة التذكرة إلى مغلقة أو معالَجة.",
        "sort_order": 50,
    },
    {
        "code": "promo.quote_activate",
        "name_ar": "تسعير/تفعيل الترويج",
        "dashboard_code": "promo",
        "description": "يتيح تسعير الحملات أو تفعيلها.",
        "sort_order": 60,
    },
    {
        "code": "verification.finalize",
        "name_ar": "اعتماد التوثيق",
        "dashboard_code": "verify",
        "description": "يتيح إنهاء طلبات التوثيق.",
        "sort_order": 70,
    },
    {
        "code": "analytics.export",
        "name_ar": "تصدير التقارير",
        "dashboard_code": "analytics",
        "description": "يتيح تصدير بيانات وتقارير التحليلات.",
        "sort_order": 80,
    },
]


def seed_permission_catalog(apps, schema_editor):
    Dashboard = apps.get_model("backoffice", "Dashboard")
    AccessPermission = apps.get_model("backoffice", "AccessPermission")
    UserAccessProfile = apps.get_model("backoffice", "UserAccessProfile")

    Dashboard.objects.get_or_create(
        code="moderation",
        defaults={"name_ar": "مركز الإشراف", "is_active": True, "sort_order": 25},
    )

    permission_map = {}
    for row in PERMISSION_ROWS:
        permission, _ = AccessPermission.objects.get_or_create(
            code=row["code"],
            defaults={
                "name_ar": row["name_ar"],
                "dashboard_code": row["dashboard_code"],
                "description": row["description"],
                "sort_order": row["sort_order"],
                "is_active": True,
            },
        )
        permission_map[row["code"]] = permission

    for profile in UserAccessProfile.objects.all():
        codes = set()
        if profile.level in {"admin", "power"}:
            codes = set(permission_map.keys())
        elif profile.level == "user":
            allowed = set(profile.allowed_dashboards.values_list("code", flat=True))
            if "support" in allowed:
                codes.update({"support.assign", "support.resolve"})
            if "content" in allowed:
                codes.add("content.hide_delete")
            if "promo" in allowed:
                codes.add("promo.quote_activate")
            if "verify" in allowed:
                codes.add("verification.finalize")
            if "analytics" in allowed or "billing" in allowed:
                codes.add("analytics.export")
            if "moderation" in allowed:
                codes.update({"moderation.assign", "moderation.resolve"})

        if codes:
            profile.granted_permissions.add(*(permission_map[code] for code in sorted(codes)))


def unseed_permission_catalog(apps, schema_editor):
    Dashboard = apps.get_model("backoffice", "Dashboard")
    AccessPermission = apps.get_model("backoffice", "AccessPermission")

    AccessPermission.objects.filter(code__in=[row["code"] for row in PERMISSION_ROWS]).delete()
    Dashboard.objects.filter(code="moderation").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name_ar", models.CharField(max_length=120)),
                ("dashboard_code", models.SlugField(blank=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="useraccessprofile",
            name="granted_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="access_profiles",
                to="backoffice.accesspermission",
            ),
        ),
        migrations.RunPython(seed_permission_catalog, unseed_permission_catalog),
    ]
