from django.urls import path

from .views import (
    BlockPortfolioItemView,
    BlockProviderView,
    BlockSpotlightItemView,
    CategoryListView,
    FollowProviderView,
    LikeProviderView,
    LikePortfolioCommentView,
    LikePortfolioItemView,
    LikeSpotlightCommentView,
    LikeSpotlightItemView,
    MyFollowingProvidersView,
    MyLikedProvidersView,
    MyLikedPortfolioItemsView,
    MyLikedSpotlightItemsView,
    MySavedPortfolioItemsView,
    MySavedSpotlightItemsView,
    MyProviderFollowersView,
    MyProviderCoverGalleryView,
    MyProviderCoverImageDetailView,
    MyProviderLikersView,
    MyProviderProfileView,
    MyProviderServiceDetailView,
    MyProviderServicesListCreateView,
    MyProviderSubcategoriesView,
    MyVisibilityBlocksView,
    MyProviderPortfolioListCreateView,
    MyProviderPortfolioDetailView,
    MyProviderSpotlightListCreateView,
    MyProviderSpotlightDetailView,
    ProviderServicePublicDetailView,
    ProviderServicesPublicListView,
    ProviderSubcategoriesPublicListView,
    ProviderCreateView,
    ProviderDetailView,
    ProviderFollowersView,
    ProviderFollowingView,
    ProviderListView,
    ProviderPortfolioFeedView,
    ProviderPortfolioListView,
    ProviderPublicStatsView,
    PublicPortfolioDetailView,
    PublicSpotlightDetailView,
    RecordProviderContentShareView,
    ReportPortfolioItemView,
    ReportSpotlightItemView,
    RegionCityCatalogView,
    PortfolioCommentDetailView,
    PortfolioCommentsView,
    ReportPortfolioCommentView,
    SpotlightCommentDetailView,
    SpotlightCommentsView,
    ReportSpotlightCommentView,
    ProviderSpotlightListView,
    ProviderSpotlightFeedView,
    SavePortfolioItemView,
    SaveSpotlightItemView,
    UnfollowProviderView,
    UnlikeProviderView,
    UnlikePortfolioCommentView,
    UnlikePortfolioItemView,
    UnlikeSpotlightCommentView,
    UnlikeSpotlightItemView,
    UnsavePortfolioItemView,
    UnsaveSpotlightItemView,
)

app_name = "providers"

urlpatterns = [
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("geo/regions-cities/", RegionCityCatalogView.as_view(), name="regions_cities"),
    path("list/", ProviderListView.as_view(), name="provider_list"),
    path("me/profile/", MyProviderProfileView.as_view(), name="my_profile"),
    path("me/cover-gallery/", MyProviderCoverGalleryView.as_view(), name="my_cover_gallery"),
    path("me/cover-gallery/<int:pk>/", MyProviderCoverImageDetailView.as_view(), name="my_cover_gallery_detail"),
    path("me/subcategories/", MyProviderSubcategoriesView.as_view(), name="my_subcategories"),
    path("me/services/", MyProviderServicesListCreateView.as_view(), name="my_services"),
    path("me/services/<int:pk>/", MyProviderServiceDetailView.as_view(), name="my_service_detail"),
    path("me/following/", MyFollowingProvidersView.as_view(), name="my_following"),
    path("me/likes/", MyLikedProvidersView.as_view(), name="my_likes"),
    path("me/followers/", MyProviderFollowersView.as_view(), name="my_followers"),
    path("me/likers/", MyProviderLikersView.as_view(), name="my_likers"),

    # Portfolio (provider projects/media)
    path("me/portfolio/", MyProviderPortfolioListCreateView.as_view(), name="my_portfolio"),
    path("me/portfolio/<int:pk>/", MyProviderPortfolioDetailView.as_view(), name="my_portfolio_detail"),
    path("me/spotlights/", MyProviderSpotlightListCreateView.as_view(), name="my_spotlights"),
    path("me/spotlights/<int:pk>/", MyProviderSpotlightDetailView.as_view(), name="my_spotlights_detail"),
    path("me/favorites/", MySavedPortfolioItemsView.as_view(), name="my_favorites_media"),
    path("me/favorites/spotlights/", MySavedSpotlightItemsView.as_view(), name="my_favorites_spotlights"),
    path("me/likes/media/", MyLikedPortfolioItemsView.as_view(), name="my_liked_media"),
    path("me/likes/spotlights/", MyLikedSpotlightItemsView.as_view(), name="my_liked_spotlights"),
    path("me/visibility-blocks/", MyVisibilityBlocksView.as_view(), name="my_visibility_blocks"),
    path("services/<int:pk>/", ProviderServicePublicDetailView.as_view(), name="provider_service_public_detail"),
    path("portfolio/feed/", ProviderPortfolioFeedView.as_view(), name="portfolio_feed"),
    path("portfolio/<int:item_id>/public/", PublicPortfolioDetailView.as_view(), name="portfolio_public_detail"),
    path("<int:provider_id>/portfolio/", ProviderPortfolioListView.as_view(), name="provider_portfolio"),
    path("<int:provider_id>/spotlights/", ProviderSpotlightListView.as_view(), name="provider_spotlights"),
    path("spotlights/feed/", ProviderSpotlightFeedView.as_view(), name="spotlights_feed"),
    path("spotlights/<int:item_id>/public/", PublicSpotlightDetailView.as_view(), name="spotlight_public_detail"),
    path("<int:provider_id>/subcategories/", ProviderSubcategoriesPublicListView.as_view(), name="provider_subcategories"),
    path("<int:provider_id>/services/", ProviderServicesPublicListView.as_view(), name="provider_services"),
    path("<int:provider_id>/followers/", ProviderFollowersView.as_view(), name="provider_followers"),
    path("<int:provider_id>/following/", ProviderFollowingView.as_view(), name="provider_following"),
    path("<int:provider_id>/stats/", ProviderPublicStatsView.as_view(), name="provider_public_stats"),
    path("portfolio/<int:item_id>/like/", LikePortfolioItemView.as_view(), name="portfolio_like"),
    path("portfolio/<int:item_id>/unlike/", UnlikePortfolioItemView.as_view(), name="portfolio_unlike"),
    path("portfolio/<int:item_id>/save/", SavePortfolioItemView.as_view(), name="portfolio_save"),
    path("portfolio/<int:item_id>/unsave/", UnsavePortfolioItemView.as_view(), name="portfolio_unsave"),
    path("portfolio/<int:item_id>/comments/", PortfolioCommentsView.as_view(), name="portfolio_comments"),
    path("portfolio/<int:item_id>/comments/<int:comment_id>/", PortfolioCommentDetailView.as_view(), name="portfolio_comment_detail"),
    path("portfolio/<int:item_id>/comments/<int:comment_id>/like/", LikePortfolioCommentView.as_view(), name="portfolio_comment_like"),
    path("portfolio/<int:item_id>/comments/<int:comment_id>/unlike/", UnlikePortfolioCommentView.as_view(), name="portfolio_comment_unlike"),
    path("portfolio/<int:item_id>/comments/<int:comment_id>/report/", ReportPortfolioCommentView.as_view(), name="portfolio_comment_report"),
    path("portfolio/<int:item_id>/report/", ReportPortfolioItemView.as_view(), name="portfolio_report"),
    path("portfolio/<int:item_id>/hide/", BlockPortfolioItemView.as_view(), name="portfolio_hide"),
    path("spotlights/<int:item_id>/like/", LikeSpotlightItemView.as_view(), name="spotlight_like"),
    path("spotlights/<int:item_id>/unlike/", UnlikeSpotlightItemView.as_view(), name="spotlight_unlike"),
    path("spotlights/<int:item_id>/save/", SaveSpotlightItemView.as_view(), name="spotlight_save"),
    path("spotlights/<int:item_id>/unsave/", UnsaveSpotlightItemView.as_view(), name="spotlight_unsave"),
    path("spotlights/<int:item_id>/comments/", SpotlightCommentsView.as_view(), name="spotlight_comments"),
    path("spotlights/<int:item_id>/comments/<int:comment_id>/", SpotlightCommentDetailView.as_view(), name="spotlight_comment_detail"),
    path("spotlights/<int:item_id>/comments/<int:comment_id>/like/", LikeSpotlightCommentView.as_view(), name="spotlight_comment_like"),
    path("spotlights/<int:item_id>/comments/<int:comment_id>/unlike/", UnlikeSpotlightCommentView.as_view(), name="spotlight_comment_unlike"),
    path("spotlights/<int:item_id>/comments/<int:comment_id>/report/", ReportSpotlightCommentView.as_view(), name="spotlight_comment_report"),
    path("spotlights/<int:item_id>/report/", ReportSpotlightItemView.as_view(), name="spotlight_report"),
    path("spotlights/<int:item_id>/hide/", BlockSpotlightItemView.as_view(), name="spotlight_hide"),
    path("<int:provider_id>/share/", RecordProviderContentShareView.as_view(), name="share"),
    path("<int:provider_id>/block/", BlockProviderView.as_view(), name="provider_block"),
    path("<int:pk>/", ProviderDetailView.as_view(), name="provider_detail"),
    path("register/", ProviderCreateView.as_view(), name="provider_register"),

    # Level-2+ social actions
    path("<int:provider_id>/follow/", FollowProviderView.as_view(), name="follow"),
    path("<int:provider_id>/unfollow/", UnfollowProviderView.as_view(), name="unfollow"),
    path("<int:provider_id>/like/", LikeProviderView.as_view(), name="like"),
    path("<int:provider_id>/unlike/", UnlikeProviderView.as_view(), name="unlike"),
]
