from django.urls import path
from .views import (
    MobileWebHomeView,
    MobileWebLoginView,
    MobileWebOnboardingView,
    MobileWebTwoFAView,
    MobileWebSignupView,
    MobileWebSearchView,
    MobileWebOrdersView,
    MobileWebOrderDetailView,
    MobileWebInteractiveView,
    MobileWebProfileView,
    MobileWebProviderDetailView,
    MobileWebNotificationsView,
    MobileWebChatsView,
    MobileWebChatDetailView,
    MobileWebAddServiceView,
    MobileWebUrgentRequestView,
    MobileWebRequestQuoteView,
    MobileWebSettingsView,
    MobileWebTermsView,
    MobileWebAboutView,
    MobileWebContactView,
    MobileWebLanguageView,
    MobileWebMyQrView,
    MobileWebNotificationSettingsView,
    # ── New views (1:1 mobile parity) ──
    MobileWebProviderDashboardView,
    MobileWebProviderOrdersView,
    MobileWebProviderOrderDetailView,
    MobileWebPlansView,
    MobileWebPlanSummaryView,
    MobileWebVerificationView,
    MobileWebVerificationPaymentView,
    MobileWebServiceDetailView,
    MobileWebServiceRequestFormView,
    MobileWebProviderRegisterView,
    MobileWebLoginSettingsView,
    MobileWebPromotionView,
    MobileWebPromotionNewRequestView,
    MobileWebAdditionalServicesView,
    MobileWebProviderServicesView,
    MobileWebProviderReviewsView,
    MobileWebProviderProfileEditView,
    MobileWebProviderPortfolioView,
    MobileWebProfileCompletionView,
    MobileWebProvidersMapView,
    MobileWebSearchProvidersView,
)

app_name = "mobile_web"

urlpatterns = [
    path("", MobileWebHomeView.as_view(), name="home"),
    path("login/", MobileWebLoginView.as_view(), name="login"),
    path("onboarding/", MobileWebOnboardingView.as_view(), name="onboarding"),
    path("twofa/", MobileWebTwoFAView.as_view(), name="twofa"),
    path("signup/", MobileWebSignupView.as_view(), name="signup"),
    path("search/", MobileWebSearchView.as_view(), name="search"),
    path("orders/", MobileWebOrdersView.as_view(), name="orders"),
    path("orders/<int:request_id>/", MobileWebOrderDetailView.as_view(), name="order_detail"),
    path("interactive/", MobileWebInteractiveView.as_view(), name="interactive"),
    path("profile/", MobileWebProfileView.as_view(), name="profile"),
    path("provider/<int:provider_id>/<str:provider_slug>/", MobileWebProviderDetailView.as_view(), name="provider_detail_slug"),
    path("provider/<int:provider_id>/", MobileWebProviderDetailView.as_view(), name="provider_detail"),
    path("notifications/", MobileWebNotificationsView.as_view(), name="notifications"),
    path(
        "notification-settings/",
        MobileWebNotificationSettingsView.as_view(),
        name="notification_settings",
    ),
    path("chats/", MobileWebChatsView.as_view(), name="chats"),
    path("chat/<int:thread_id>/", MobileWebChatDetailView.as_view(), name="chat_detail"),
    path("add-service/", MobileWebAddServiceView.as_view(), name="add_service"),
    path("urgent-request/", MobileWebUrgentRequestView.as_view(), name="urgent_request"),
    path("request-quote/", MobileWebRequestQuoteView.as_view(), name="request_quote"),
    path("settings/", MobileWebSettingsView.as_view(), name="settings"),
    path("terms/", MobileWebTermsView.as_view(), name="terms"),
    path("about/", MobileWebAboutView.as_view(), name="about"),
    path("contact/", MobileWebContactView.as_view(), name="contact"),
    path("language/", MobileWebLanguageView.as_view(), name="language"),
    path("my-qr/", MobileWebMyQrView.as_view(), name="my_qr"),
    # ── New routes (1:1 mobile parity) ──
    path("provider-dashboard/", MobileWebProviderDashboardView.as_view(), name="provider_dashboard"),
    path("provider-orders/", MobileWebProviderOrdersView.as_view(), name="provider_orders"),
    path("provider-orders/<int:request_id>/", MobileWebProviderOrderDetailView.as_view(), name="provider_order_detail"),
    path("plans/", MobileWebPlansView.as_view(), name="plans"),
    path("plans/summary/", MobileWebPlanSummaryView.as_view(), name="plan_summary"),
    path("verification/", MobileWebVerificationView.as_view(), name="verification"),
    path("verification/payment/", MobileWebVerificationPaymentView.as_view(), name="verification_payment"),
    path("service/<int:service_id>/", MobileWebServiceDetailView.as_view(), name="service_detail"),
    path("service-request/", MobileWebServiceRequestFormView.as_view(), name="service_request_form"),
    path("provider-register/", MobileWebProviderRegisterView.as_view(), name="provider_register"),
    path("login-settings/", MobileWebLoginSettingsView.as_view(), name="login_settings"),
    path("promotion/", MobileWebPromotionView.as_view(), name="promotion"),
    path("promotion/new/", MobileWebPromotionNewRequestView.as_view(), name="promotion_new_request"),
    path("additional-services/", MobileWebAdditionalServicesView.as_view(), name="additional_services"),
    path("provider-services/", MobileWebProviderServicesView.as_view(), name="provider_services"),
    path("provider-reviews/", MobileWebProviderReviewsView.as_view(), name="provider_reviews"),
    path("provider-profile-edit/", MobileWebProviderProfileEditView.as_view(), name="provider_profile_edit"),
    path("provider-portfolio/", MobileWebProviderPortfolioView.as_view(), name="provider_portfolio"),
    path("profile-completion/", MobileWebProfileCompletionView.as_view(), name="profile_completion"),
    path("providers-map/", MobileWebProvidersMapView.as_view(), name="providers_map"),
    path("search-providers/", MobileWebSearchProvidersView.as_view(), name="search_providers"),
]
